(** The descent at link size 24 and above, in the kernel: the 1,976
    size-24 representatives (four shards, generated by
    tools/iota4/linkcert_coq.py from classes_23_27 and linkcerts_23_27)
    together with the 305 at sizes 25–27 of LinkCerts25.  See
    docs/roadmap.md §68.3. *)
From Coq Require Import List Lia Bool.
Import ListNotations.
From Sunflower Require Import Sunflower IotaRate LinkCombine LinkLP
  LinkCerts25 LinkCerts24s0 LinkCerts24s1 LinkCerts24s2 LinkCerts24s3.

Lemma reps_okb_app : forall a b, reps_okb (a ++ b) = reps_okb a && reps_okb b.
Proof. intros; unfold reps_okb; apply forallb_app. Qed.

Definition cls24_all : list (Family * cert) :=
  cls_all ++ c24s0_all ++ c24s1_all ++ c24s2_all ++ c24s3_all.

Lemma cls24_all_ok : reps_okb cls24_all = true.
Proof.
  unfold cls24_all. repeat rewrite reps_okb_app.
  rewrite cls_all_ok, c24s0_all_ok, c24s1_all_ok, c24s2_all_ok, c24s3_all_ok. reflexivity.
Qed.

Theorem descent_24 : IotaAtMost 4 27 -> Census cls24_all 24 -> LinkDescent 4 24 54.
Proof. intros Hi Hc; exact (descent_of_census Hi cls24_all 24 ltac:(lia) cls24_all_ok Hc). Qed.

Theorem g_four_at_most_79_of_census_24 :
  IotaAtMost 4 27 -> Census cls24_all 24 -> MeetingBound 4 56 -> GAtMost 4 79.
Proof.
  intros Hi Hc Hm.
  pose proof (g_at_most_of_descent_and_meeting 4 24 54 56 (descent_24 Hi Hc) Hm) as H.
  replace (Nat.max 54 (24 - 1 + 56)) with 79 in H by reflexivity. exact H.
Qed.
