(** The link LP at size 23, in the kernel for the 12,513 classes that
    carry an LP certificate (24 shards generated by
    tools/iota4/linkcert_coq.py from classes_23_27 and linkcerts_23_27).
    The 11 remaining classes at 23 need the finer model of roadmap §65,
    which is not formalised, so no [Census … 23] hypothesis is true for
    this list and no [descent_23] is stated; what is stated is the
    per-family bound for every family whose largest link is one of these
    classes.  See docs/roadmap.md §68.3. *)
From Coq Require Import List Lia Bool.
Import ListNotations.
From Sunflower Require Import Sets Sunflower IotaRate Stability4 DirectSum LinkCombine LinkLP
  LinkCerts25 LinkCerts24 LinkCerts23s0 LinkCerts23s1 LinkCerts23s2 LinkCerts23s3 LinkCerts23s4 LinkCerts23s5 LinkCerts23s6 LinkCerts23s7 LinkCerts23s8 LinkCerts23s9 LinkCerts23s10 LinkCerts23s11 LinkCerts23s12 LinkCerts23s13 LinkCerts23s14 LinkCerts23s15 LinkCerts23s16 LinkCerts23s17 LinkCerts23s18 LinkCerts23s19 LinkCerts23s20 LinkCerts23s21 LinkCerts23s22 LinkCerts23s23.

Definition cls23_all : list (Family * cert) :=
  cls24_all ++ c23s0_all ++ c23s1_all ++ c23s2_all ++ c23s3_all ++ c23s4_all ++ c23s5_all ++ c23s6_all ++ c23s7_all ++ c23s8_all ++ c23s9_all ++ c23s10_all ++ c23s11_all ++ c23s12_all ++ c23s13_all ++ c23s14_all ++ c23s15_all ++ c23s16_all ++ c23s17_all ++ c23s18_all ++ c23s19_all ++ c23s20_all ++ c23s21_all ++ c23s22_all ++ c23s23_all.

Lemma reps_okb_app_true :
  forall a b, reps_okb a = true -> reps_okb b = true -> reps_okb (a ++ b) = true.
Proof. intros a b Ha Hb; rewrite reps_okb_app, Ha, Hb; reflexivity. Qed.

Lemma cls23_all_ok : reps_okb cls23_all = true.
Proof.
  unfold cls23_all.
  apply reps_okb_app_true; [exact cls24_all_ok |].
  apply reps_okb_app_true; [exact c23s0_all_ok |].
  apply reps_okb_app_true; [exact c23s1_all_ok |].
  apply reps_okb_app_true; [exact c23s2_all_ok |].
  apply reps_okb_app_true; [exact c23s3_all_ok |].
  apply reps_okb_app_true; [exact c23s4_all_ok |].
  apply reps_okb_app_true; [exact c23s5_all_ok |].
  apply reps_okb_app_true; [exact c23s6_all_ok |].
  apply reps_okb_app_true; [exact c23s7_all_ok |].
  apply reps_okb_app_true; [exact c23s8_all_ok |].
  apply reps_okb_app_true; [exact c23s9_all_ok |].
  apply reps_okb_app_true; [exact c23s10_all_ok |].
  apply reps_okb_app_true; [exact c23s11_all_ok |].
  apply reps_okb_app_true; [exact c23s12_all_ok |].
  apply reps_okb_app_true; [exact c23s13_all_ok |].
  apply reps_okb_app_true; [exact c23s14_all_ok |].
  apply reps_okb_app_true; [exact c23s15_all_ok |].
  apply reps_okb_app_true; [exact c23s16_all_ok |].
  apply reps_okb_app_true; [exact c23s17_all_ok |].
  apply reps_okb_app_true; [exact c23s18_all_ok |].
  apply reps_okb_app_true; [exact c23s19_all_ok |].
  apply reps_okb_app_true; [exact c23s20_all_ok |].
  apply reps_okb_app_true; [exact c23s21_all_ok |].
  apply reps_okb_app_true; [exact c23s22_all_ok |].
  exact c23s23_all_ok.
Qed.

(** Extracting one entry from a checked list, stated over an abstract list
    so that the concrete 14,794-entry list is never unfolded. *)
Lemma reps_okb_entry :
  forall reps Dk ck, reps_okb reps = true -> In (Dk, ck) reps ->
    SetNoDup Dk /\ certcheck Dk ck (54 - length Dk) = true.
Proof.
  intros reps Dk ck Hok Hin. unfold reps_okb in Hok. rewrite forallb_forall in Hok.
  specialize (Hok (Dk, ck) Hin). simpl in Hok. apply andb_true_iff in Hok as [Hnd Hck].
  split; [apply setnodupb_correct; exact Hnd | exact Hck].
Qed.

(** A family whose largest link is, up to relabelling, one of the
    14,794 certified classes at sizes 23–27 has at most 54 members. *)
Theorem bound_of_covered_link :
  IotaAtMost 4 27 ->
  forall (F : Family) (R : list nat) (Dk : Family) (ck : cert) (g h : nat -> nat),
    In (Dk, ck) cls23_all ->
    (forall x, h (g x) = x) -> (forall x, g (h x) = x) ->
    Uniform 4 F -> Distinct F -> ~ ContainsKSunflower 3 F -> In R F ->
    (forall C, In C F -> length (DisjointFrom C F) <= length (DisjointFrom R F)) ->
    DisjointFrom R F <> [] ->
    SubFamilySetEq (DisjointFrom R F) (rmapF g Dk) ->
    SubFamilySetEq (rmapF g Dk) (DisjointFrom R F) ->
    length F <= 54.
Proof.
  intros Hi F R Dk ck g h Hin Hgh Hhg HU HD Hno HR Hmax Hne H1 H2.
  destruct (reps_okb_entry cls23_all Dk ck cls23_all_ok Hin) as [Hnd Hck].
  exact (class_bound Hi Dk ck Hnd Hck F R g h Hgh Hhg HU HD Hno HR Hmax Hne H1 H2).
Qed.
