//! Kramer–Mesner: search for a record family under a prescribed
//! automorphism group.
//!
//! `docs/roadmap.md` §12 says the record at `b = 6` falls at 317 members
//! and the Abbott–Hanson–Sauer substitution gives 300. `extend.rs` shows
//! the 300-family cannot be extended — on any ground set, and even
//! ignoring sunflower-freeness — so a 317-member family, if one exists,
//! has different symmetry. The 300-family's own group has order
//! `6 * 60^3 = 1296000`; the standard move when a highly symmetric object
//! caps out is to prescribe a *smaller* group and search the orbits.
//!
//! That is Kramer–Mesner, and it is how most record designs are found.
//! The reduction is the point: with a group `G` of order `|G|` prescribed
//! on `[g]`, a `G`-invariant family is a union of `G`-orbits on
//! `b`-subsets, so `C(18,6) = 18564` booleans become a few hundred
//! integers.
//!
//! ## Why this is a backtracking search and not an ILP
//!
//! In the classical setting the constraint is linear (every `t`-set
//! covered `lambda` times) and the orbit reduction produces an integer
//! program. Here the constraint is **ternary and negative** — no three
//! members may form a sunflower — so the orbit-level formulation is a
//! constraint satisfaction problem, not a covering problem. Writing it
//! as an ILP or a SAT instance would need one clause per sunflower
//! triple, and at `(b,g) = (6,18)` there are `C(18564,3) ~ 1e12` triples
//! to test before the first clause is written.
//!
//! So the orbits are searched directly, and the ternary condition is
//! checked *incrementally*, which is what makes it affordable:
//!
//! ```text
//!   A, B, x is a sunflower   iff   A ∩ B ⊆ x   and   x ∩ (A △ B) = ∅
//! ```
//!
//! — the same reduction `extend.rs` uses. Keeping the pairs of the
//! current family in buckets indexed by `A ∩ B`, a candidate `x` is
//! tested by looking up the `2^b` subsets of `x` and checking `x ∩ Δ = ∅`
//! for the pairs found. At `b = 6` that is 64 lookups into buckets
//! averaging four entries, against the 50000 pairs a naive scan would
//! walk.
//!
//! ## What a negative result here is worth
//!
//! Exhausting a group is a real statement — "no `G`-invariant family of
//! 317 exists" — provided the budget is reported. Every run below
//! records whether it finished, and the caller is expected to say so.

use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};

/// A multiply-shift hasher for `u64` keys. The default `SipHash` costs
/// more than the bucket lookups it guards -- `can_add` does `2^b` of
/// them per candidate, and at `b = 6` that is the inner loop of the
/// whole search.
#[derive(Default)]
pub struct FastHasher(u64);

impl Hasher for FastHasher {
    fn finish(&self) -> u64 {
        self.0
    }
    fn write(&mut self, bytes: &[u8]) {
        for &b in bytes {
            self.0 = (self.0 ^ u64::from(b)).wrapping_mul(0x100_0000_01b3);
        }
    }
    fn write_u64(&mut self, n: u64) {
        // splitmix64 finaliser
        let mut z = n.wrapping_add(0x9e37_79b9_7f4a_7c15);
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        self.0 = z ^ (z >> 31);
    }
}

type FastMap<K, V> = HashMap<K, V, BuildHasherDefault<FastHasher>>;

/// A permutation of `[n]`, as the list of images.
pub type Perm = Vec<u32>;

/// The image of a subset under a permutation.
#[inline]
pub fn apply(p: &Perm, set: u64) -> u64 {
    let mut out = 0u64;
    let mut m = set;
    while m != 0 {
        let bit = m.trailing_zeros();
        m &= m - 1;
        out |= 1u64 << p[bit as usize];
    }
    out
}

fn compose(p: &Perm, q: &Perm) -> Perm {
    q.iter().map(|&x| p[x as usize]).collect()
}

/// Every element of the group generated by `gens`, by closure. Returns
/// `None` if the group exceeds `cap` — a prescribed group that large is
/// not one this search wants.
pub fn group_closure(n: u32, gens: &[Perm], cap: usize) -> Option<Vec<Perm>> {
    let identity: Perm = (0..n).collect();
    let mut seen: Vec<Perm> = vec![identity.clone()];
    let mut frontier: Vec<Perm> = vec![identity];
    while let Some(p) = frontier.pop() {
        for g in gens {
            let q = compose(g, &p);
            if !seen.contains(&q) {
                if seen.len() >= cap {
                    return None;
                }
                seen.push(q.clone());
                frontier.push(q);
            }
        }
    }
    seen.sort();
    Some(seen)
}

/// The orbits of `group` on the `b`-subsets of `[n]`, each sorted.
pub fn orbits_on_subsets(n: u32, b: u32, group: &[Perm]) -> Vec<Vec<u64>> {
    let mut seen: HashMap<u64, ()> = HashMap::new();
    let mut out = Vec::new();
    let mut cur = 0u64;
    fn rec(n: u32, b: u32, start: u32, cur: &mut u64, depth: u32, all: &mut Vec<u64>) {
        if depth == b {
            all.push(*cur);
            return;
        }
        for x in start..n {
            *cur |= 1u64 << x;
            rec(n, b, x + 1, cur, depth + 1, all);
            *cur &= !(1u64 << x);
        }
    }
    let mut all = Vec::new();
    rec(n, b, 0, &mut cur, 0, &mut all);
    for s in all {
        if seen.contains_key(&s) {
            continue;
        }
        let mut orb: Vec<u64> = group.iter().map(|p| apply(p, s)).collect();
        orb.sort_unstable();
        orb.dedup();
        for &t in &orb {
            seen.insert(t, ());
        }
        out.push(orb);
    }
    out
}

/// A family under construction, with the machinery to add and undo a
/// member in time proportional to its size rather than its square.
///
/// `buckets[I]` holds the symmetric differences of the pairs whose
/// intersection is `I`. A candidate `x` completes a sunflower with some
/// pair exactly when one of those buckets, indexed by a subset of `x`,
/// contains a `Δ` disjoint from `x`.
pub struct Incremental {
    pub members: Vec<u64>,
    buckets: FastMap<u64, Vec<u64>>,
    /// The bucket key of every pair inserted, in insertion order, so an
    /// undo is a sequence of pops.
    trail: Vec<u64>,
    /// How many trail entries each member added.
    marks: Vec<usize>,
    intersecting: bool,
}

impl Incremental {
    pub fn new(intersecting: bool) -> Self {
        Incremental {
            members: Vec::new(),
            buckets: FastMap::default(),
            trail: Vec::new(),
            marks: Vec::new(),
            intersecting,
        }
    }

    pub fn len(&self) -> usize {
        self.members.len()
    }

    pub fn is_empty(&self) -> bool {
        self.members.is_empty()
    }

    /// May `x` be added: distinct, meeting everything (when asked), and
    /// completing no 3-sunflower?
    pub fn can_add(&self, x: u64) -> bool {
        for &a in &self.members {
            if a == x {
                return false;
            }
            if self.intersecting && a & x == 0 {
                return false;
            }
        }
        // Every subset of `x` is a possible pair-intersection, and the
        // standard `(sub - 1) & x` walk enumerates them as masks with no
        // allocation -- which matters, because this is the inner loop.
        let mut sub = x;
        loop {
            if let Some(deltas) = self.buckets.get(&sub) {
                for &d in deltas {
                    if d & x == 0 {
                        return false;
                    }
                }
            }
            if sub == 0 {
                break;
            }
            sub = (sub - 1) & x;
        }
        true
    }

    pub fn push(&mut self, x: u64) {
        let before = self.trail.len();
        for &a in &self.members {
            let key = a & x;
            let delta = a ^ x;
            self.buckets.entry(key).or_default().push(delta);
            self.trail.push(key);
        }
        self.marks.push(self.trail.len() - before);
        self.members.push(x);
    }

    pub fn pop(&mut self) {
        let k = self.marks.pop().expect("pop on an empty family");
        for _ in 0..k {
            let key = self.trail.pop().expect("trail underflow");
            let v = self.buckets.get_mut(&key).expect("bucket vanished");
            v.pop();
            if v.is_empty() {
                self.buckets.remove(&key);
            }
        }
        self.members.pop();
    }

    /// Add a whole orbit, or restore the family and report failure.
    pub fn push_orbit(&mut self, orb: &[u64]) -> bool {
        let mut added = 0;
        for &x in orb {
            if self.can_add(x) {
                self.push(x);
                added += 1;
            } else {
                for _ in 0..added {
                    self.pop();
                }
                return false;
            }
        }
        true
    }

    pub fn pop_orbit(&mut self, orb: &[u64]) {
        for _ in 0..orb.len() {
            self.pop();
        }
    }
}

/// The result of one prescribed-group search.
#[derive(Debug, Clone)]
pub struct OrbitResult {
    pub best: usize,
    pub best_family: Vec<u64>,
    pub nodes: u64,
    pub exhaustive: bool,
}

/// Search the unions of orbits for a family of at least `target`
/// members, intersecting (when asked) and 3-sunflower-free.
///
/// Orbits are tried in a fixed order and each is either taken whole or
/// skipped, which is what makes the search a search over `G`-invariant
/// families rather than over families. The bound is the usual one — what
/// is in hand plus everything still to come — and it is what makes an
/// exhausted run mean something: no union of these orbits reaches the
/// target.
pub fn search_orbits(
    orbits: &[Vec<u64>],
    target: usize,
    intersecting: bool,
    budget: u64,
) -> OrbitResult {
    // Largest orbits first: the bound bites sooner, and an orbit that is
    // inconsistent with itself is discovered at the root rather than at
    // a leaf.
    let mut ord: Vec<usize> = (0..orbits.len()).collect();
    ord.sort_by_key(|&i| std::cmp::Reverse(orbits[i].len()));

    struct S<'a> {
        orbits: &'a [Vec<u64>],
        target: usize,
        nodes: u64,
        budget: u64,
        best: usize,
        best_family: Vec<u64>,
        done: bool,
    }

    // The candidate list carries only the orbits still addable, and
    // "addable" is monotone -- once a member of an orbit clashes with the
    // family it clashes with every extension of it -- so filtering is
    // sound and never has to be undone. This is the max-clique shape,
    // not a subset walk: the loop over `cands` covers "skip this orbit"
    // implicitly, so there is no exponential branch on skipping.
    fn rec(s: &mut S, fam: &mut Incremental, cands: &[usize]) {
        s.nodes += 1;
        if s.nodes > s.budget {
            return;
        }
        if fam.len() > s.best {
            s.best = fam.len();
            s.best_family = fam.members.clone();
        }
        if fam.len() >= s.target {
            s.done = true;
            return;
        }
        let mut rest: usize = cands.iter().map(|&i| s.orbits[i].len()).sum();
        for idx in 0..cands.len() {
            if fam.len() + rest < s.target {
                return;
            }
            let o = cands[idx];
            rest -= s.orbits[o].len();
            if !fam.push_orbit(&s.orbits[o]) {
                continue;
            }
            let next: Vec<usize> = cands[idx + 1..]
                .iter()
                .copied()
                .filter(|&j| s.orbits[j].iter().all(|&x| fam.can_add(x)))
                .collect();
            rec(s, fam, &next);
            if s.done || s.nodes > s.budget {
                return;
            }
            fam.pop_orbit(&s.orbits[o]);
        }
    }

    let mut st = S {
        orbits,
        target,
        nodes: 0,
        budget,
        best: 0,
        best_family: Vec::new(),
        done: false,
    };
    let mut fam = Incremental::new(intersecting);
    rec(&mut st, &mut fam, &ord);
    OrbitResult {
        best: st.best,
        best_family: st.best_family,
        nodes: st.nodes,
        exhaustive: st.nodes <= st.budget,
    }
}

/// Verify a family from scratch: `b`-uniform, distinct, sunflower-free,
/// and optionally intersecting. Shares no code with the search.
pub fn verify(f: &[u64], b: u32, intersecting: bool) -> Result<(), String> {
    for (i, a) in f.iter().enumerate() {
        if a.count_ones() != b {
            return Err(format!("member {i} has size {}", a.count_ones()));
        }
        for (j, y) in f.iter().enumerate().skip(i + 1) {
            if a == y {
                return Err(format!("members {i} and {j} are equal"));
            }
            if intersecting && a & y == 0 {
                return Err(format!("members {i} and {j} are disjoint"));
            }
            let ab = a & y;
            for (l, c) in f.iter().enumerate().skip(j + 1) {
                if ab == (a & c) && ab == (y & c) {
                    return Err(format!("members {i},{j},{l} are a 3-sunflower"));
                }
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------
// Groups worth prescribing.
// ---------------------------------------------------------------------

/// `i -> i + 1 mod n`.
pub fn cyclic_gen(n: u32) -> Perm {
    (0..n).map(|i| (i + 1) % n).collect()
}

/// `i -> -i mod n`.
pub fn reflect_gen(n: u32) -> Perm {
    (0..n).map(|i| (n - i) % n).collect()
}

/// `i -> a*i mod p` on `[p]`, fixing 0. Only a permutation when
/// `gcd(a,p) = 1`.
pub fn mult_gen(p: u32, a: u32) -> Perm {
    (0..p).map(|i| (i * a) % p).collect()
}

/// The block-permutation generators of `Sym(k) wr Sym(t)` acting on
/// `t` blocks of `k` points: the cycle inside block 0 and the swap of
/// blocks 0 and 1, plus the cycle of all blocks.
pub fn block_gens(blocks: u32, size: u32) -> Vec<Perm> {
    let n = blocks * size;
    // cycle inside block 0
    let inner: Perm = (0..n)
        .map(|i| if i < size { (i + 1) % size } else { i })
        .collect();
    // cycle the blocks
    let outer: Perm = (0..n)
        .map(|i| {
            let (blk, off) = (i / size, i % size);
            ((blk + 1) % blocks) * size + off
        })
        .collect();
    // swap blocks 0 and 1
    let swap: Perm = (0..n)
        .map(|i| {
            let (blk, off) = (i / size, i % size);
            match blk {
                0 => size + off,
                1 => off,
                _ => i,
            }
        })
        .collect();
    vec![inner, outer, swap]
}

/// `PGL(2,q)` on the projective line `P^1(F_q)`, `q` prime: points
/// `0..q-1` are `F_q` and point `q` is infinity. Generated by
/// `x -> x+1`, `x -> a x` for a primitive root `a`, and `x -> -1/x`.
/// `PSL(2,q)` is the same with `a` replaced by `a^2`.
pub fn pgl2_gens(q: u32, primitive: u32, projective_special: bool) -> Vec<Perm> {
    let n = q + 1;
    let inf = q;
    let translate: Perm = (0..n).map(|i| if i == inf { inf } else { (i + 1) % q }).collect();
    let a = if projective_special {
        (primitive * primitive) % q
    } else {
        primitive
    };
    let scale: Perm = (0..n).map(|i| if i == inf { inf } else { (i * a) % q }).collect();
    let invert: Perm = (0..n)
        .map(|i| {
            if i == inf {
                0
            } else if i == 0 {
                inf
            } else {
                // -1/i mod q
                let mut inv = 1;
                while (i * inv) % q != 1 {
                    inv += 1;
                }
                (q - inv) % q
            }
        })
        .collect();
    vec![translate, scale, invert]
}

/// `C_k wr C_t`: the wreath product of two cyclic groups acting on `t`
/// blocks of `k` points — order `k^t * t`. The full `Sym(k) wr Sym(t)`
/// is the 300-family's own symmetry and is far too large to prescribe
/// (order `720^3 * 6` at `(k,t) = (6,3)`); this is the natural small
/// subgroup with the same block structure.
pub fn cyclic_wreath_gens(blocks: u32, size: u32) -> Vec<Perm> {
    let n = blocks * size;
    let inner: Perm = (0..n)
        .map(|i| if i < size { (i + 1) % size } else { i })
        .collect();
    let outer: Perm = (0..n)
        .map(|i| {
            let (blk, off) = (i / size, i % size);
            ((blk + 1) % blocks) * size + off
        })
        .collect();
    vec![inner, outer]
}

/// `C_a x C_b` acting on an `a` by `b` grid of `a*b` points.
pub fn grid_gens(a: u32, b: u32) -> Vec<Perm> {
    let n = a * b;
    let rows: Perm = (0..n).map(|i| ((i / b + 1) % a) * b + i % b).collect();
    let cols: Perm = (0..n).map(|i| (i / b) * b + (i % b + 1) % b).collect();
    vec![rows, cols]
}

fn is_prime(p: u32) -> bool {
    p >= 2 && (2..p).take_while(|d| d * d <= p).all(|d| p % d != 0)
}

fn primitive_root(p: u32) -> u32 {
    for a in 2..p {
        let mut x = a % p;
        let mut k = 1;
        while x != 1 {
            x = x * a % p;
            k += 1;
        }
        if k == p - 1 {
            return a;
        }
    }
    1
}

/// A list of groups worth prescribing on `[n]`, as `(name, generators)`.
///
/// Chosen for *many orbits of moderate size*: the whole point of a
/// prescribed group is that a family which is a union of a few orbits is
/// found in a search over a few hundred integers rather than over
/// `C(n,b)` booleans. Very large groups leave too few orbits to reach a
/// target; very small ones leave too many to search.
pub fn standard_groups(n: u32) -> Vec<(String, Vec<Perm>)> {
    let mut out: Vec<(String, Vec<Perm>)> = Vec::new();
    out.push((format!("C_{n}"), vec![cyclic_gen(n)]));
    out.push((format!("D_{n}"), vec![cyclic_gen(n), reflect_gen(n)]));

    // Products of cyclic groups on a grid, and the cyclic wreath with
    // the same block structure.
    for a in 2..n {
        if n % a != 0 {
            continue;
        }
        let b = n / a;
        if a <= b {
            out.push((format!("C_{a} x C_{b} (grid)"), grid_gens(a, b)));
        }
        if a >= 2 && b >= 2 {
            out.push((format!("C_{b} wr C_{a} (blocks)"), cyclic_wreath_gens(a, b)));
        }
    }

    // Affine groups on a prime ground set: C_p semidirect C_k for every
    // k dividing p-1.
    if is_prime(n) {
        let g = primitive_root(n);
        let mut k = 2;
        while k <= n - 1 {
            if (n - 1) % k == 0 {
                let a = {
                    // an element of order k: g^((p-1)/k)
                    let e = (n - 1) / k;
                    let mut x = 1u32;
                    for _ in 0..e {
                        x = x * g % n;
                    }
                    x
                };
                out.push((
                    format!("C_{n} : C_{k} (affine)"),
                    vec![cyclic_gen(n), mult_gen(n, a)],
                ));
            }
            k += 1;
        }
    }

    // Projective groups when n = q + 1 with q prime.
    if n >= 3 && is_prime(n - 1) {
        let q = n - 1;
        let g = primitive_root(q);
        out.push((format!("PSL(2,{q})"), pgl2_gens(q, g, true)));
        out.push((format!("PGL(2,{q})"), pgl2_gens(q, g, false)));
    }
    out
}

/* ------------------------------------------------------------------ */
/* Root-split parallel search, with a resumable frontier.              */
/* ------------------------------------------------------------------ */

/// The parallel form of [`search_orbits`], and the reason it is sound
/// with no communication between workers.
///
/// Every pruning test in [`search_orbits`] is against the **fixed**
/// `target`: the bound is `fam.len() + rest < target`, and `best` is
/// written but never read by any prune. So sibling subtrees at the root
/// share no incumbent — there is nothing for one worker to learn from
/// another, no speedup anomaly, and no risk of exploring a node the
/// sequential run would have pruned. That is the ideal case for parallel
/// branch and bound, and it is why this is forty lines rather than a
/// research project.
///
/// **The split is also the checkpoint.** The root subproblems *are* the
/// frontier: subproblem `i` is "the families whose first taken orbit is
/// `ord[i]`", and the subproblems partition the search space. Recording
/// which have finished is therefore a complete resume point, and
/// `checkpoint` writes one index per line as each completes. A restarted
/// run reads the file and does only what is left. `docs/roadmap.md` §23.3
/// records these as two separate future tasks; they are one change.
///
/// Note what this does **not** buy: four workers die together, so
/// parallelism alone would not have survived the restart that killed the
/// `iota(4,10)` attempt. It shrinks the window you must fit inside;
/// the checkpoint is what survives.
///
/// `exhaustive` means every root subproblem ran to completion inside the
/// budget — including ones completed by an earlier run and read back
/// from the checkpoint.
pub fn search_orbits_parallel(
    orbits: &[Vec<u64>],
    target: usize,
    intersecting: bool,
    budget: u64,
    threads: usize,
    checkpoint: Option<&std::path::Path>,
) -> OrbitResult {
    use std::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};
    use std::sync::Mutex;

    let mut ord: Vec<usize> = (0..orbits.len()).collect();
    ord.sort_by_key(|&i| std::cmp::Reverse(orbits[i].len()));

    // `suffix[i]` = how many members orbits `ord[i..]` could still add.
    // The sequential root loop stops as soon as this drops below the
    // target, so root indices past that point are not subproblems at all.
    let n = ord.len();
    let mut suffix = vec![0usize; n + 1];
    for i in (0..n).rev() {
        suffix[i] = suffix[i + 1] + orbits[ord[i]].len();
    }
    let roots = (0..n).filter(|&i| suffix[i] >= target).count();

    // Root subproblems already finished by a previous run.
    let done_before: std::collections::HashSet<usize> = match checkpoint {
        Some(p) => std::fs::read_to_string(p)
            .unwrap_or_default()
            .lines()
            .filter_map(|l| l.trim().parse::<usize>().ok())
            .collect(),
        None => std::collections::HashSet::new(),
    };

    let next = AtomicUsize::new(0);
    let nodes = AtomicU64::new(0);
    let found = AtomicBool::new(false);
    let best = Mutex::new((0usize, Vec::<u64>::new()));
    let log = Mutex::new(());

    // Same recursion as `search_orbits`, with the two pieces of state a
    // worker cannot keep to itself: the node budget and the found flag.
    //
    // The return value is what makes the checkpoint sound: `true` means
    // this subtree was explored to completion, `false` means it was
    // abandoned (budget spent, or another worker already succeeded). Only
    // a completed root subproblem may be recorded — writing one that was
    // abandoned would let a restart skip work that was never done, which
    // is a wrong answer rather than a slow one.
    #[allow(clippy::too_many_arguments)]
    fn rec(
        orbits: &[Vec<u64>],
        target: usize,
        fam: &mut Incremental,
        cands: &[usize],
        nodes: &AtomicU64,
        budget: u64,
        found: &AtomicBool,
        local_best: &mut (usize, Vec<u64>),
    ) -> bool {
        if found.load(Ordering::Relaxed) || nodes.fetch_add(1, Ordering::Relaxed) >= budget {
            return false;
        }
        if fam.len() > local_best.0 {
            local_best.0 = fam.len();
            local_best.1 = fam.members.clone();
        }
        if fam.len() >= target {
            found.store(true, Ordering::Relaxed);
            return false;
        }
        let mut rest: usize = cands.iter().map(|&i| orbits[i].len()).sum();
        for idx in 0..cands.len() {
            // The bound fired: nothing left in this subtree can reach the
            // target, so the subtree *is* accounted for.
            if fam.len() + rest < target {
                return true;
            }
            let o = cands[idx];
            rest -= orbits[o].len();
            if !fam.push_orbit(&orbits[o]) {
                continue;
            }
            let nx: Vec<usize> = cands[idx + 1..]
                .iter()
                .copied()
                .filter(|&j| orbits[j].iter().all(|&x| fam.can_add(x)))
                .collect();
            let complete = rec(orbits, target, fam, &nx, nodes, budget, found, local_best);
            fam.pop_orbit(&orbits[o]);
            if !complete {
                return false;
            }
        }
        true
    }

    let truncated = AtomicBool::new(false);
    let finished = AtomicBool::new(false);
    let roots_done = AtomicUsize::new(done_before.len());
    std::thread::scope(|scope| {
        // A run that reports nothing until it returns is a run you cannot
        // tell from a hung one, and on a long instance that is the whole
        // difficulty: the `iota(4,10) >= 28` attempt of docs/roadmap.md
        // §24.11 spent hours with no way to see whether it was making
        // progress. One monitor thread fixes it and costs nothing --
        // it sleeps, and reads two atomics.
        if checkpoint.is_some() {
            scope.spawn(|| {
                let mut last = 0u64;
                while !finished.load(Ordering::Relaxed) {
                    std::thread::sleep(std::time::Duration::from_secs(30));
                    if finished.load(Ordering::Relaxed) {
                        break;
                    }
                    let n = nodes.load(Ordering::Relaxed);
                    eprintln!(
                        "[progress] nodes={n} (+{}) roots {}/{}",
                        n - last,
                        roots_done.load(Ordering::Relaxed),
                        roots
                    );
                    last = n;
                }
            });
        }
        for _ in 0..threads.max(1) {
            scope.spawn(|| {
                // One `Incremental` per worker: the buckets are the whole
                // cost of the incremental sunflower test and must not be
                // shared.
                let mut fam = Incremental::new(intersecting);
                let mut local_best = (0usize, Vec::<u64>::new());
                loop {
                    let i = next.fetch_add(1, Ordering::Relaxed);
                    if i >= roots || found.load(Ordering::Relaxed) {
                        break;
                    }
                    if nodes.load(Ordering::Relaxed) >= budget {
                        truncated.store(true, Ordering::Relaxed);
                        break;
                    }
                    if done_before.contains(&i) {
                        continue;
                    }
                    // Subproblem i: take orbit ord[i], then recurse on the
                    // orbits after it that are still compatible.
                    //
                    // The pop belongs *inside* the success branch:
                    // `push_orbit` already unwinds everything it added
                    // when it fails, so popping again on the failure path
                    // would pop entries belonging to nothing and corrupt
                    // the worker for every later subproblem.
                    let complete = if fam.push_orbit(&orbits[ord[i]]) {
                        if fam.len() > local_best.0 {
                            local_best = (fam.len(), fam.members.clone());
                        }
                        let c = if fam.len() >= target {
                            found.store(true, Ordering::Relaxed);
                            false
                        } else {
                            let cands: Vec<usize> = ord[i + 1..]
                                .iter()
                                .copied()
                                .filter(|&j| orbits[j].iter().all(|&x| fam.can_add(x)))
                                .collect();
                            rec(
                                orbits,
                                target,
                                &mut fam,
                                &cands,
                                &nodes,
                                budget,
                                &found,
                                &mut local_best,
                            )
                        };
                        fam.pop_orbit(&orbits[ord[i]]);
                        c
                    } else {
                        // The orbit is inconsistent with itself, so the
                        // subproblem is empty and trivially complete.
                        true
                    };
                    debug_assert_eq!(fam.len(), 0);

                    if !complete {
                        if !found.load(Ordering::Relaxed) {
                            truncated.store(true, Ordering::Relaxed);
                        }
                        break;
                    }
                    roots_done.fetch_add(1, Ordering::Relaxed);
                    if let Some(p) = checkpoint {
                        let _g = log.lock().unwrap();
                        use std::io::Write;
                        if let Ok(mut f) =
                            std::fs::OpenOptions::new().create(true).append(true).open(p)
                        {
                            let _ = writeln!(f, "{i}");
                            let _ = f.flush();
                        }
                    }
                }
                let mut g = best.lock().unwrap();
                if local_best.0 > g.0 {
                    *g = local_best;
                }
                drop(g);
                // The last worker out stops the monitor; setting it more
                // than once is harmless.
                finished.store(true, Ordering::Relaxed);
            });
        }
    });

    let (b, bf) = best.into_inner().unwrap();
    OrbitResult {
        best: b,
        best_family: bf,
        nodes: nodes.load(Ordering::Relaxed),
        exhaustive: !truncated.load(Ordering::Relaxed)
            && nodes.load(Ordering::Relaxed) < budget,
    }
}
