#!/usr/bin/env python3
"""Export link-LP certificates (docs/roadmap.md §64) as integer certificates
for the kernel checker coq/LinkLP.v.

  linkcert_coq.py CLASSES.gz CERTS.json.gz OUT.v [NAME [SIZE [i/n]]]

Each rational dual certificate (y_C, z_T, w) is scaled by the least common
denominator K; the Coq record is (cK, cy, cz, cw) with cy keyed by member and cz by trace.
The file defines every class and certificate and states

  Lemma NAME_all_ok : reps_okb NAME_all = true.
  Proof. vm_compute. reflexivity. Qed.

which is the computational hypothesis of LinkLP.descent_of_census.

and re-checks the scaled certificate in exact integer arithmetic here
before writing it, so a class that fails is reported, not emitted.
"""
import sys, json, gzip, math, os
from fractions import Fraction as Fr
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import linkcert

def scale(F, B, c):
    y = [Fr(v) for v in c["y"]]; z = [Fr(v) for v in c["z"]]; w = Fr(c["w"])
    K = 1
    for q in y + z + [w]:
        K = K * q.denominator // math.gcd(K, q.denominator)
    yi = [int(q * K) for q in y]; zi = [int(q * K) for q in z]; wi = int(w * K)
    bound = 54 - len(F)
    assert min(yi + zi + [wi]) >= 0
    assert sum(yi) + wi >= K
    for j, T in enumerate(B):
        assert sum(yi[i] for i, C in enumerate(F) if not (T & C)) + zi[j] >= K
    assert len(F) * sum(yi) + sum(linkcert.CAP[len(T)] * zi[j] for j, T in enumerate(B)) + 27 * wi <= K * bound
    return K, yi, zi, wi

def coq_list(xs): return "[" + "; ".join(map(str, xs)) + "]"

def main():
    cls, certs, out = sys.argv[1:4]
    name = sys.argv[4] if len(sys.argv) > 4 else "cls"
    size = int(sys.argv[5]) if len(sys.argv) > 5 else None      # keep only this link size
    shard = sys.argv[6] if len(sys.argv) > 6 else None           # "i/n": every n-th class, offset i
    fams = linkcert.load(cls)
    C = json.load(gzip.open(certs, "rt"))
    assert len(C) == len(fams)
    if size is not None:
        keep = [k for k, F in enumerate(fams) if len(F) == size]
        fams = [fams[k] for k in keep]; C = [C[k] for k in keep]
    if shard is not None:
        i, n = map(int, shard.split("/"))
        fams = fams[i::n]; C = C[i::n]
    emit_closing = shard is None
    lines = ["(* Generated by tools/iota4/linkcert_coq.py; do not edit. *)",
             "From Coq Require Import List.", "Import ListNotations.",
             "From Coq Require Import Lia.", "From Sunflower Require Import Sunflower IotaRate LinkCombine LinkLP.", ""]
    names = []
    for k, (F, c) in enumerate(zip(fams, C)):
        linkcert.validate(F)
        B = linkcert.unwitnessed(F)
        K, yi, zi, wi = scale(F, B, c)
        D = coq_list(coq_list(sorted(S)) for S in F)
        Y = coq_list(f"({coq_list(sorted(S))}, {yi[i]})" for i, S in enumerate(F) if yi[i])
        Z = coq_list(f"({coq_list(sorted(T))}, {zi[j]})" for j, T in enumerate(B) if zi[j])
        n = f"{name}_{k}"
        lines.append(f"Definition {n}_D : Family := {D}.")
        lines.append(f"Definition {n}_c : cert := mkcert {K} {Y} {Z} {wi}.")
        names.append(n)
    lines.append("")
    lines.append(f"Definition {name}_all : list (Family * cert) :=")
    lines.append("  [" + ";\n   ".join(f"({n}_D, {n}_c)" for n in names) + "].")
    lines.append("")
    lines.append(f"(** Every representative is distinct and its certificate checks:")
    lines.append(f"    the hypothesis [reps_okb reps = true] of [LinkLP.descent_of_census]. *)")
    lines.append(f"Lemma {name}_all_ok : reps_okb {name}_all = true.")
    lines.append("Proof. vm_compute. reflexivity. Qed.")
    lines.append("")
    if not emit_closing:
        open(out, "w").write("\n".join(lines))
        print("wrote", out, "classes", len(names), "(shard, no closing theorems)")
        return
    lo = min(len(F) for F in fams)
    lines.append(f"(** The descent at link size {lo} and above, conditional only on [ι(4) ≤ 27]")
    lines.append(f"    and on the census being complete from size {lo} up. *)")
    lines.append(f"Theorem descent_{lo} : IotaAtMost 4 27 -> Census {name}_all {lo} -> LinkDescent 4 {lo} 54.")
    lines.append(f"Proof. intros Hi Hc; exact (descent_of_census Hi {name}_all {lo} ltac:(lia) {name}_all_ok Hc). Qed.")
    lines.append("")
    lines.append(f"Theorem g_four_at_most_{lo-1+56}_of_census_{lo} :")
    lines.append(f"  IotaAtMost 4 27 -> Census {name}_all {lo} -> MeetingBound 4 56 -> GAtMost 4 {lo-1+56}.")
    lines.append("Proof.")
    lines.append(f"  intros Hi Hc Hm.")
    lines.append(f"  pose proof (g_at_most_of_descent_and_meeting 4 {lo} 54 56 (descent_{lo} Hi Hc) Hm) as H.")
    lines.append(f"  replace (Nat.max 54 ({lo} - 1 + 56)) with {lo-1+56} in H by reflexivity. exact H.")
    lines.append("Qed.")
    lines.append("")
    open(out, "w").write("\n".join(lines))
    print("wrote", out, "classes", len(names), "sizes", sorted(set(len(F) for F in fams)))

if __name__ == "__main__":
    main()
